In [10]:
import numpy
from numpy.linalg import inv
from fractions import Fraction

# Notation setup

n = 4
print "G = SL(%d) \n" % n
''' Define basis beta and varpi '''
beta = numpy.zeros((n-1,n))
varpi = numpy.zeros((n-1,n))
for i in range(n-1):
    for j in range(n):
        if j == i:
            beta[i,j] = 1
        elif j == i + 1:
            beta[i,j] = -1
        else:
            beta[i,j] = 0
    for j in range(n):
        if j <= i:
            varpi[i,j] = (n-i-1)/float(n)
        else: 
            varpi[i,j] = -(i+1)/float(n)

print "The basis for beta is: "
print beta
print "\nThe basis for varpi is: "
print varpi

def theta(basis):
    '''This function takes an ordered basis and flips the order.'''
    temp = numpy.copy(basis)
    length = len(basis)
    for i in range(length):
        temp[i] = basis[length-1-i]
    return temp

def V_to_a(basis, vector):
    ''' Express vector as a linear combination of basis elements, 
            returns the (n-1) coefficients
            i.e., V to aaa '''
    basis = basis[:,:-1]
    basis = numpy.transpose(inv(basis))
    vector = vector[:-1]
    return numpy.dot(basis,vector)

def last_coordinate(vector):
    ''' This appends the last coordinate to the vector so the sum of all coordinates is zero '''
    return numpy.append(vector, -numpy.sum(vector))

#basis_1 is the original basis and basis_2 is the target basis 
def change_of_basis(basis_1, basis_2):
    ''' This returns the change-of-basis matrix. '''
    '''This is a nice solution actually'''
    A = None
    for i in range(len(basis_1)):
        if i == 0: 
            A = V_to_a(basis_1, basis_2[i])
        else:
            A = numpy.concatenate((A, V_to_a(basis_1, basis_2[i])), axis=0)
    return numpy.reshape(A,(n-1, n-1))

# def w_vector(vector, sigma):
#     ''' Permutes the coordinates of vector according to sigma '''
#     sigma = numpy.append(sigma, sigma[0])
#     new_vector = numpy.copy(vector)
#     for i, item in enumerate(sigma[:-1]):
#         new_vector[item] = vector[sigma[i+1]]
#     return new_vector

def w_vector(mu, sigma):
    ''' Permutes the coordinates of vector in V according to sigma '''
    new_mu = numpy.copy(mu)
    for i, item in enumerate(sigma):
        new_mu[item] = mu[i]
    return new_mu

def w(matrix, sigma):
    ''' Permutes every vector in the matrix according to sigma '''
    new_matrix = numpy.copy(matrix)
    for i in range(len(matrix)):
        new_matrix[i] = w_vector(matrix[i], sigma)
    return new_matrix
        
# vector = (Id - theta.w)(varpi)
# vector = varpi - theta (w(varpi, [0,1]))
# change_of_basis(beta, vector)

def a_to_V(basis, coefficients):
    '''Returns vector in my hyperplane, given coefficients
        i.e., V \to \aaa '''
    vector = numpy.zeros(len(basis)+1)
    for i in range(len(basis)):
        vector = vector + coefficients[i] * numpy.array(basis[i])
    return vector

def mymatrix(coefficients, sigma): # coefficients = rows of identity matrix
    mylambda = a_to_V(varpi, coefficients)
    wlambda = w_vector( mylambda, sigma)
    vector = V_to_a(theta(varpi), wlambda)
    vector = coefficients - vector
    vector = a_to_V(varpi, vector) 
    return V_to_a(beta, vector)

def FL_matrix(coefficients, sigma): # coefficients = rows of identity matrix
    mylambda = a_to_V(varpi, coefficients)
    wlambda = w_vector( mylambda, sigma)
    vector = V_to_a(varpi, wlambda)
    vector = coefficients - vector
    vector = a_to_V(varpi, vector) 
    return V_to_a(beta, vector)

def error_matrix(coefficients, sigma): # coefficients = rows of identity matrix
    mylambda = a_to_V(varpi, coefficients)
    wlambda = w_vector( mylambda, sigma)
    return V_to_a(beta, wlambda) - V_to_a(theta(beta),wlambda)

w = (2,0,1,3) # w = (sigma(0), sigma(1), ...) really
print "\n---------------------------------"
print "w is ", w
print "---------------------------------"
print "the FL matrix for lambda - w(lambda) is:"
finalmatrix = []
for row in numpy.identity(n-1):
    print FL_matrix(row, w)
    
print "\n-----------------------------------"
print "the error matrix for (1 - theta)(w(lambda)) is:"
finalmatrix = []
for row in numpy.identity(n-1):
    print error_matrix(row, w)

print "\n-----------------------------------"
print "the matrix for lambda - theta.w(lambda) is:"
finalmatrix = []
for row in numpy.identity(n-1):
    print mymatrix(row, w)

print "\n-----------------------------------"


''' Do not forget this: If the output matrix is (a_{i,j}) then coefficient of beta_1 is a_11 c_1 + a_12 c_2 etc. '''

G = SL(4) 

The basis for beta is: 
[[ 1. -1.  0.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1. -1.]]

The basis for varpi is: 
[[ 0.75 -0.25 -0.25 -0.25]
 [ 0.5   0.5  -0.5  -0.5 ]
 [ 0.25  0.25  0.25 -0.75]]

---------------------------------
w is  (2, 0, 1, 3)
---------------------------------
the FL matrix for lambda - w(lambda) is:
[ 1.  1.  0.]
[  2.77555756e-17   1.00000000e+00   0.00000000e+00]
[ 0.  0.  0.]

-----------------------------------
the error matrix for (1 - theta)(w(lambda)) is:
[-0.5  0.   0.5]
[ 0.  0.  0.]
[-0.5  0.   0.5]

-----------------------------------
the matrix for lambda - theta.w(lambda) is:
[ 0.5  1.   0.5]
[  1.11022302e-16   1.00000000e+00   0.00000000e+00]
[-0.5  0.   0.5]

-----------------------------------


' Do not forget this: If the output matrix is (a_{i,j}) then coefficient of beta_1 is a_11 c_1 + a_12 c_2 etc. '